import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "./models/User";
import bcrypt from "bcryptjs";

dotenv.config();

export const judgesData = [
  {
    pj: "55940",
    lastName: "Ogola",
    firstName: "Hon. Eric",
    otherNames: "Kennedy Okumu",
    gender: "MALE",
    email: "eric.ogola@court.go.ke",
    phone: "0722280058",
    idNo: "8781595",
    station: "Principal Judge, Milimani Family Division",
  },
  {
    pj: "56001",
    lastName: "Korir",
    firstName: "Hon. Roseline",
    otherNames: "C. Langat",
    gender: "FEMALE",
    email: "roseline.korir@court.go.ke",
    phone: "0722428139",
    idNo: "7476305",
    station: "Bomet",
  },
  {
    pj: "14009",
    lastName: "Ougo",
    firstName: "Hon. Rose",
    otherNames: "Edwina",
    gender: "FEMALE",
    email: "rougo@court.go.ke",
    phone: "0722522828",
    idNo: "2246656",
    station: "Bungoma",
  },
  {
    pj: "33095",
    lastName: "Kemei",
    firstName: "Hon. David",
    otherNames: "Kipyegomen",
    gender: "MALE",
    email: "dkemei@court.go.ke",
    phone: "0724787088",
    idNo: "9778440",
    station: "Bungoma",
  },
  {
    pj: "59326",
    lastName: "Musyoka",
    firstName: "Hon. William",
    otherNames: "Musya",
    gender: "MALE",
    email: "william.musyoka@court.go.ke",
    phone: "0722499025",
    idNo: "8365136",
    station: "Busia",
  },
  {
    pj: "12926",
    lastName: "Gitari",
    firstName: "Hon. Lucy",
    otherNames: "Waruguru",
    gender: "FEMALE",
    email: "lucy.gitari@court.go.ke",
    phone: "0721446084",
    idNo: "5482714",
    station: "Chuka",
  },
  {
    pj: "14978",
    lastName: "Nyakundi",
    firstName: "Hon. Reuben",
    otherNames: "Nyambati",
    gender: "MALE",
    email: "rnyakundi@court.go.ke",
    phone: "0722484334",
    idNo: "2760750",
    station: "Eldoret",
  },
  {
    pj: "81735",
    lastName: "Anundo",
    firstName: "Hon. John.R",
    otherNames: "Wananda",
    gender: "MALE",
    email: "wananda.john@court.go.ke",
    phone: "0721210501",
    idNo: "13594591",
    station: "Eldoret",
  },
  {
    pj: "19871",
    lastName: "Ominde",
    firstName: "Hon. Emily",
    otherNames: "Onyando",
    gender: "FEMALE",
    email: "emily.ominde@court.go.ke",
    phone: "0722756410",
    idNo: null,
    station: "Eldoret",
  },
  {
    pj: "65416",
    lastName: "Njuguna",
    firstName: "Hon. Lucy",
    otherNames: "Mwihaki",
    gender: "FEMALE",
    email: "lucy.njuguna@court.go.ke",
    phone: "0722757033",
    idNo: "8989124",
    station: "Embu",
  },
  {
    pj: "20424",
    lastName: "Onyiego",
    firstName: "Hon. John",
    otherNames: "Nyabuto",
    gender: "MALE",
    email: "john.onyiego@court.go.ke",
    phone: "0722359542",
    idNo: "5948626",
    station: "Garissa",
  },
  {
    pj: "14960",
    lastName: "Kiarie",
    firstName: "Hon. Waweru",
    otherNames: "Kiarie",
    gender: "MALE",
    email: "wkiarie@court.go.ke",
    phone: "0722600129",
    idNo: "5302738",
    station: "Homabay",
  },
  {
    pj: "20369",
    lastName: "Cherere",
    firstName: "Hon. Thripsisa",
    otherNames: "Wanjiku Wamae",
    gender: "FEMALE",
    email: "thripsisa.wamae@court.go.ke",
    phone: "0733846414",
    idNo: "7030464",
    station: "Isiolo",
  },
  {
    pj: "20880",
    lastName: "Ngetich",
    firstName: "Hon. Rachel",
    otherNames: "Chepkoech",
    gender: "FEMALE",
    email: "rachael.ngetich@court.go.ke",
    phone: "0722666734",
    idNo: "9836966",
    station: "Kabarnet",
  },
  {
    pj: "16425",
    lastName: "Mutuku",
    firstName: "Hon. Stella",
    otherNames: "Ngali",
    gender: "FEMALE",
    email: "stella.mutuku@court.go.ke",
    phone: "0727804154",
    idNo: "2303343",
    station: "Kajiado",
  },
  {
    pj: "20775",
    lastName: "Tamar",
    firstName: "Hon. John",
    otherNames: "Lolwalan",
    gender: "MALE",
    email: "john.tamar@court.go.ke",
    phone: "0726883859",
    idNo: null,
    station: "Kajiado",
  },
  {
    pj: "81734",
    lastName: "Chirchir",
    firstName: "Hon. Sophie",
    otherNames: "Chebet",
    gender: "FEMALE",
    email: "sophie.chirchir@court.go.ke",
    phone: "0722873874",
    idNo: "10012985",
    station: "Kakamega",
  },
  {
    pj: "82774",
    lastName: "Bett",
    firstName: "Alice",
    otherNames: "Chepngetich",
    gender: "FEMALE",
    email: "alice.soi@court.go.ke",
    phone: "0722301391",
    idNo: null,
    station: "Kakamega",
  },
  {
    pj: "21755",
    lastName: "Mbungi",
    firstName: "Stephen",
    otherNames: "Nzisi",
    gender: "MALE",
    email: "smbungi@court.go.ke",
    phone: "0722270127",
    idNo: null,
    station: "Kakamega",
  },
  {
    pj: "10885",
    lastName: "Wendoh",
    firstName: "Roseline",
    otherNames: "P.V",
    gender: "FEMALE",
    email: "rwendoh@court.go.ke",
    phone: "0733838404",
    idNo: "4826632",
    station: "Kapenguria",
  },
  {
    pj: "10916",
    lastName: "Karanja",
    firstName: "Joseph",
    otherNames: "Raphael",
    gender: "MALE",
    email: "joseph.karanja@court.go.ke",
    phone: "0734760775",
    idNo: "4826606",
    station: "Kapsabet",
  },
  {
    pj: "38841",
    lastName: "Sergon",
    firstName: "Joseph",
    otherNames: "Kiplagat",
    gender: "MALE",
    email: "joseph.sergon@court.go.ke",
    phone: "0722654600",
    idNo: "7233993",
    station: "Kericho",
  },
  {
    pj: "55990",
    lastName: "Mwongo",
    firstName: "Richard",
    otherNames: "Mururu",
    gender: "MALE",
    email: "rmwongo@court.go.ke",
    phone: "0734594685",
    idNo: "3490267",
    station: "Kerugoya",
  },
  {
    pj: "56027",
    lastName: "Mshila",
    firstName: "Abigal",
    otherNames: "Shiganga",
    gender: "FEMALE",
    email: "amshila@court.go.ke",
    phone: "0705132513",
    idNo: "4826501",
    station: "Kiambu",
  },
  {
    pj: "19732",
    lastName: "Chepkwony",
    firstName: "Dorah",
    otherNames: "Odityo",
    gender: "FEMALE",
    email: "dorah.chepkwony@court.go.ke",
    phone: "0722745988",
    idNo: "5793121",
    station: "Kiambu",
  },
  {
    pj: "20660",
    lastName: "Kavedza",
    firstName: "Diana",
    otherNames: "Rachel",
    gender: "FEMALE",
    email: "diana.kavedza@court.go.ke",
    phone: "0724659565",
    idNo: "8982813",
    station: "Kibra",
  },
  {
    pj: "40140",
    lastName: "Odera",
    firstName: "Teresia",
    otherNames: "Ochieng",
    gender: "FEMALE",
    email: "teresa.odera@court.go.ke",
    phone: "0722422301",
    idNo: "12458164",
    station: "Kisii",
  },
  {
    pj: "65238",
    lastName: "Aburili",
    firstName: "Roselyne",
    otherNames: "Makokha Ekirapa",
    gender: "FEMALE",
    email: "roselyne.aburili@court.go.ke",
    phone: "0715580626",
    idNo: "9244251",
    station: "Kisumu",
  },
  {
    pj: "81740",
    lastName: "Shariff",
    firstName: "Mwanaisha",
    otherNames: "Saida",
    gender: "FEMALE",
    email: "mwanaisha.saida@court.go.ke",
    phone: "0720956184",
    idNo: "1037911",
    station: "Kisumu",
  },
  {
    pj: "65270",
    lastName: "Mrima",
    firstName: "Antony",
    otherNames: "Charo",
    gender: "MALE",
    email: "antony.murima@court.go.ke",
    phone: "0719376886",
    idNo: "11763752",
    station: "Kitale",
  },
  {
    pj: "65254",
    lastName: "Limo",
    firstName: "Robert",
    otherNames: "Kipkoech",
    gender: "MALE",
    email: "robert.limo@court.go.ke",
    phone: "0722768866",
    idNo: "9709837",
    station: "Kitui",
  },
  {
    pj: "65377",
    lastName: "Otieno",
    firstName: "Patrick",
    otherNames: "Okwarro",
    gender: "MALE",
    email: "patrick.otieno@court.go.ke",
    phone: "0734565357",
    idNo: "8820032",
    station: "Lodwar",
  },
  {
    pj: "16522",
    lastName: "Muigai",
    firstName: "Margaret",
    otherNames: "Waringa",
    gender: "FEMALE",
    email: "margaret.muigai@court.go.ke",
    phone: "0725901587",
    idNo: "3642077",
    station: "Machakos",
  },
  {
    pj: "81738",
    lastName: "Olel",
    firstName: "Francis",
    otherNames: "Odhiambo",
    gender: "MALE",
    email: "francis.rayola@court.go.ke",
    phone: "0722934875",
    idNo: "13039532",
    station: "Machakos",
  },
  {
    pj: "82767",
    lastName: "Inziani",
    firstName: "Noel",
    otherNames: "Onditi Adagi",
    gender: "FEMALE",
    email: "noel.adagi@court.go.ke",
    phone: "0721241018",
    idNo: null,
    station: "Machakos",
  },
  {
    pj: "61171",
    lastName: "Riechi",
    firstName: "Stephen",
    otherNames: "Nyaga",
    gender: "MALE",
    email: "stephen.riechi@court.go.ke",
    phone: "0722801122",
    idNo: "11598030",
    station: "Kisumu",
  },
  {
    pj: "61234",
    lastName: "Mutai",
    firstName: "Phillip",
    otherNames: "Kipkurui",
    gender: "MALE",
    email: "phillip.mutai@court.go.ke",
    phone: "0722325500",
    idNo: "22694489",
    station: "Kericho",
  },
  {
    pj: "61302",
    lastName: "Omondi",
    firstName: "Richard",
    otherNames: "Ochieng",
    gender: "MALE",
    email: "richard.omondi@court.go.ke",
    phone: "0722541800",
    idNo: "11878245",
    station: "Homa Bay",
  },
  {
    pj: "61411",
    lastName: "Kimani",
    firstName: "Joseph",
    otherNames: "Mungai",
    gender: "MALE",
    email: "joseph.kimani@court.go.ke",
    phone: "0722455221",
    idNo: "27654419",
    station: "Murang’a",
  },
  {
    pj: "61509",
    lastName: "Chepkwony",
    firstName: "Mercy",
    otherNames: "Cherono",
    gender: "FEMALE",
    email: "mercy.chepkwony@court.go.ke",
    phone: "0722301199",
    idNo: "28900112",
    station: "Eldoret",
  },
  {
    pj: "61544",
    lastName: "Mwangi",
    firstName: "Samuel",
    otherNames: "Kariuki",
    gender: "MALE",
    email: "samuel.mwangi@court.go.ke",
    phone: "0722667788",
    idNo: "22156314",
    station: "Nyeri",
  },
  {
    pj: "61622",
    lastName: "Kiptoo",
    firstName: "Edwin",
    otherNames: "Kiplagat",
    gender: "MALE",
    email: "edwin.kiptoo@court.go.ke",
    phone: "0722310044",
    idNo: null,
    station: "Kabarnet",
  },
  {
    pj: "61733",
    lastName: "Muthoni",
    firstName: "Alice",
    otherNames: "Wanjiru",
    gender: "FEMALE",
    email: "alice.muthoni@court.go.ke",
    phone: "0722405522",
    idNo: "23321211",
    station: "Embu",
  },
  {
    pj: "61810",
    lastName: "Achieng",
    firstName: "Grace",
    otherNames: "Atieno",
    gender: "FEMALE",
    email: "grace.achieng@court.go.ke",
    phone: "0722739922",
    idNo: "22441102",
    station: "Migori",
  },
  {
    pj: "61908",
    lastName: "Barasa",
    firstName: "Tom",
    otherNames: "Wekesa",
    gender: "MALE",
    email: "tom.barasa@court.go.ke",
    phone: "0722993411",
    idNo: "17654322",
    station: "Bungoma",
  },
  {
    pj: "62012",
    lastName: "Mutuku",
    firstName: "Lydia",
    otherNames: "Nthenya",
    gender: "FEMALE",
    email: "lydia.mutuku@court.go.ke",
    phone: "0722441900",
    idNo: "21900011",
    station: "Machakos",
  },
  {
    pj: "62088",
    lastName: "Cheruiyot",
    firstName: "Benard",
    otherNames: "Kipruto",
    gender: "MALE",
    email: "benard.cheruiyot@court.go.ke",
    phone: "0722370001",
    idNo: "24411909",
    station: "Nakuru",
  },
  {
    pj: "62177",
    lastName: "Wekesa",
    firstName: "Sarah",
    otherNames: "Nafula",
    gender: "FEMALE",
    email: "sarah.wekesa@court.go.ke",
    phone: "0722549988",
    idNo: "29011234",
    station: "Kitale",
  },
  {
    pj: "62255",
    lastName: "Obiero",
    firstName: "Daniel",
    otherNames: "Odhiambo",
    gender: "MALE",
    email: "daniel.obiero@court.go.ke",
    phone: "0722571001",
    idNo: null,
    station: "Siaya",
  },
  {
    pj: "62301",
    lastName: "Mutinda",
    firstName: "Patrick",
    otherNames: "Musyoka",
    gender: "MALE",
    email: "patrick.mutinda@court.go.ke",
    phone: "0722856611",
    idNo: "18923456",
    station: "Makueni",
  },
  {
    pj: "62419",
    lastName: "Njagi",
    firstName: "Robert",
    otherNames: "Mugo",
    gender: "MALE",
    email: "robert.njagi@court.go.ke",
    phone: "0722334412",
    idNo: "11800221",
    station: "Chuka",
  },
  {
    pj: "62533",
    lastName: "Kerubo",
    firstName: "Janet",
    otherNames: "Nyaboke",
    gender: "FEMALE",
    email: "janet.kerubo@court.go.ke",
    phone: "0722991022",
    idNo: "27119855",
    station: "Kisii",
  },
  {
    pj: "62644",
    lastName: "Omondi",
    firstName: "Peter",
    otherNames: "Otieno",
    gender: "MALE",
    email: "peter.omondi@court.go.ke",
    phone: "0722193300",
    idNo: "11345021",
    station: "Mbita",
  },
  {
    pj: "62750",
    lastName: "Mwangi",
    firstName: "Faith",
    otherNames: "Njeri",
    gender: "FEMALE",
    email: "faith.mwangi@court.go.ke",
    phone: "0722440066",
    idNo: "23559180",
    station: "Nyahururu",
  },
  {
    pj: "62899",
    lastName: "Koech",
    firstName: "Geoffrey",
    otherNames: "Kipngeno",
    gender: "MALE",
    email: "geoffrey.koech@court.go.ke",
    phone: "0722770088",
    idNo: "17752209",
    station: "Bomet",
  },
  {
    pj: "62940",
    lastName: "Chebet",
    firstName: "Irene",
    otherNames: "Jepchirchir",
    gender: "FEMALE",
    email: "irene.chebet@court.go.ke",
    phone: "0722384411",
    idNo: "22134190",
    station: "Kapenguria",
  },
  {
    pj: "63012",
    lastName: "Okoth",
    firstName: "Brian",
    otherNames: "Odongo",
    gender: "MALE",
    email: "brian.okoth@court.go.ke",
    phone: "0722119988",
    idNo: null,
    station: "Kisumu",
  },
  {
    pj: "63177",
    lastName: "Njoroge",
    firstName: "Winnie",
    otherNames: "Wambui",
    gender: "FEMALE",
    email: "winnie.njoroge@court.go.ke",
    phone: "0722897733",
    idNo: "25548790",
    station: "Nairobi - Milimani",
  },
  {
    pj: "63244",
    lastName: "Mutheu",
    firstName: "Hon. Carol",
    otherNames: "Ndinda",
    gender: "FEMALE",
    email: "carol.mutheu@court.go.ke",
    phone: "0722013344",
    idNo: "28890011",
    station: "Machakos",
  },
  {
    pj: "63321",
    lastName: "Owino",
    firstName: "Hon. James",
    otherNames: "Ouma",
    gender: "MALE",
    email: "james.owino@court.go.ke",
    phone: "0722447812",
    idNo: "19988452",
    station: "Kisumu",
  },
  {
    pj: "63409",
    lastName: "Kilonzo",
    firstName: "Hon. George",
    otherNames: "Mutua",
    gender: "MALE",
    email: "george.kilonzo@court.go.ke",
    phone: "0722881199",
    idNo: "11900231",
    station: "Mwingi",
  },
  {
    pj: "63488",
    lastName: "Cherop",
    firstName: "Hon. Judith",
    otherNames: "Jebet",
    gender: "FEMALE",
    email: "judith.cherop@court.go.ke",
    phone: "0722301177",
    idNo: "21899101",
    station: "Eldama Ravine",
  },
  {
    pj: "63510",
    lastName: "Barongo",
    firstName: "Hon. Kennedy",
    otherNames: "Marita",
    gender: "MALE",
    email: "kennedy.barongo@court.go.ke",
    phone: "0722987110",
    idNo: "24467120",
    station: "Kisii",
  },
  {
    pj: "63655",
    lastName: "Wambua",
    firstName: "Hon. Joyce",
    otherNames: "Ndunge",
    gender: "FEMALE",
    email: "joyce.wambua@court.go.ke",
    phone: "0722440912",
    idNo: "19902334",
    station: "Kitui",
  },
  {
    pj: "63729",
    lastName: "Mogaka",
    firstName: "Hon. Henry",
    otherNames: "Onsongo",
    gender: "MALE",
    email: "henry.mogaka@court.go.ke",
    phone: "0722009988",
    idNo: null,
    station: "Kisii",
  },
  {
    pj: "63814",
    lastName: "Kariuki",
    firstName: "Hon. Lilian",
    otherNames: "Wairimu",
    gender: "FEMALE",
    email: "lilian.kariuki@court.go.ke",
    phone: "0722510077",
    idNo: "21670012",
    station: "Thika",
  },
  {
    pj: "63977",
    lastName: "Oseko",
    firstName: "Hon. David",
    otherNames: "Nyambega",
    gender: "MALE",
    email: "david.oseko@court.go.ke",
    phone: "0722784400",
    idNo: "13220019",
    station: "Kisii",
  },
  {
    pj: "64033",
    lastName: "Kiplangat",
    firstName: "Hon. Solomon",
    otherNames: "Koech",
    gender: "MALE",
    email: "solomon.kiplangat@court.go.ke",
    phone: "0722338766",
    idNo: "25118834",
    station: "Kericho",
  },
  {
    pj: "64119",
    lastName: "Nyaga",
    firstName: "Hon. Beatrice",
    otherNames: "Muthoni",
    gender: "FEMALE",
    email: "beatrice.nyaga@court.go.ke",
    phone: "0722001134",
    idNo: "27891022",
    station: "Embu",
  },
  {
    pj: "64288",
    lastName: "Opiyo",
    firstName: "Hon. Daniel",
    otherNames: "Ooko",
    gender: "MALE",
    email: "daniel.opiyo@court.go.ke",
    phone: "0722607788",
    idNo: null,
    station: "Homa Bay",
  },
  {
    pj: "64353",
    lastName: "Mwikali",
    firstName: "Hon. Ruth",
    otherNames: "Syombua",
    gender: "FEMALE",
    email: "ruth.mwikali@court.go.ke",
    phone: "0722334488",
    idNo: "20776654",
    station: "Machakos",
  },
  {
    pj: "64402",
    lastName: "Ochieng",
    firstName: "Hon. Thomas",
    otherNames: "Oduor",
    gender: "MALE",
    email: "thomas.ochieng@court.go.ke",
    phone: "0722449001",
    idNo: "12233445",
    station: "Kisumu",
  },
  {
    pj: "64510",
    lastName: "Chepkemoi",
    firstName: "Hon. Mary",
    otherNames: "Jemutai",
    gender: "FEMALE",
    email: "mary.chepkemoi@court.go.ke",
    phone: "0722776655",
    idNo: "27654019",
    station: "Bomet",
  },
  {
    pj: "64641",
    lastName: "Muli",
    firstName: "Hon. Benard",
    otherNames: "Kyalo",
    gender: "MALE",
    email: "benard.muli@court.go.ke",
    phone: "0722997011",
    idNo: null,
    station: "Machakos",
  },
  {
    pj: "64790",
    lastName: "Atieno",
    firstName: "Hon. Lucy",
    otherNames: "Akinyi",
    gender: "FEMALE",
    email: "lucy.atieno@court.go.ke",
    phone: "0722901122",
    idNo: "22881190",
    station: "Migori",
  },
  {
    pj: "43244",
    lastName: "Otieno",
    firstName: "Hon. Clara",
    otherNames: "Omondi",
    gender: "FEMALE",
    email: "claraotieno23@gmail.com ",
    phone: "",
    idNo: "",
    station: "High Court",
  },
];

const seedJudges = async () => {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) throw new Error("MONGO_URI missing in .env");

    await mongoose.connect(mongoUri);
    console.log("🔥 MongoDB Connected");

    // Clear previous judge data
    await User.deleteMany();
    console.log("🗑️ Old judge records cleared");

    // Prepare judges data with hashed PJ as password + computed name field
    const judgesToInsert = await Promise.all(
      judgesData.map(async (j) => {
        const hashedPassword = await bcrypt.hash(j.pj, 12);

        const computedName = `${j.firstName} ${j.otherNames || ""} ${
          j.lastName
        }`
          .replace(/\s+/g, " ")
          .trim();

        return {
          firstName: j.firstName,
          lastName: j.lastName,
          otherNames: j.otherNames || "",
          name: computedName,
          email: j.email.toLowerCase(),
          pj: j.pj, // <- required by schema
          password: hashedPassword,
          role: "judge",
        };
      })
    );

    await User.insertMany(judgesToInsert);
    console.log(
      `🎉 Inserted ${judgesToInsert.length} judge records successfully!`
    );

    process.exit(0);
  } catch (err) {
    console.error("❌ Seeder error:", err);
    process.exit(1);
  }
};

seedJudges();
